# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/orb-intro/
orbs:
  node: circleci/node@4.9

workflows:
  version: 2
  build-and-test:
    jobs:
      - lint_and_test

jobs:
  lint_and_test:
    docker:
      - image: cimg/node:18.17
      - image: postgres:14.6-alpine
        environment:
          POSTGRES_USER: circleci
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci --no-optional
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm run test
          environment:
            TEST_DATABASE_URL: postgres://circleci@localhost:5432/circleci


